In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('/content/vehicle_emission_dataset.csv')
df.head()

Vehicle Type Fuel Type  Engine Size  Age of Vehicle  Mileage       Speed  \
0   Motorcycle  Electric     2.747609              22   291288   49.083255   
1          Bus  Electric     5.743714               3   188398   23.460311   
2          Bus    Hybrid     4.606368              17   281451  115.508350   
3        Truck  Electric     3.913024               4   151321   18.540217   
4        Truck    Hybrid     1.611297              15    91810  109.596566   

   Acceleration Road Type Traffic Conditions  Temperature   Humidity  \
0      1.887738   Highway           Moderate    13.880458  52.883905   
1      3.544147      City              Heavy    19.136947   5.697343   
2      4.646886   Highway          Free flow     8.123428   3.953116   
3      3.581004     Rural              Heavy    35.994893   0.509678   
4      3.879303   Highway           Moderate    14.793481  52.450884   

   Wind Speed  Air Pressure  CO2 Emissions  NOx Emissions  PM2.5 Emissions  \
0   18.938861    955.411642     179.930088       1.085520         0.011548   
1   14.716526   1035.763062     250.505219       1.285628         0.187112   
2   18.644522    976.207064     404.979103       0.258189         0.132398   
3   11.951859    966.919462     463.568608       1.040956         0.166325   
4    2.761138    953.229351      79.514604       1.583390         0.078043   

   VOC Emissions  SO2 Emissions Emission Level  
0       0.096207       0.022936         Medium  
1       0.073321       0.028021         Medium  
2       0.014744       0.075334           High  
3       0.093490       0.025324           High  
4       0.020396       0.024986            Low

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Vehicle Type        10000 non-null  object 
 1   Fuel Type           10000 non-null  object 
 2   Engine Size         10000 non-null  float64
 3   Age of Vehicle      10000 non-null  int64  
 4   Mileage             10000 non-null  int64  
 5   Speed               10000 non-null  float64
 6   Acceleration        10000 non-null  float64
 7   Road Type           10000 non-null  object 
 8   Traffic Conditions  10000 non-null  object 
 9   Temperature         10000 non-null  float64
 10  Humidity            10000 non-null  float64
 11  Wind Speed          10000 non-null  float64
 12  Air Pressure        10000 non-null  float64
 13  CO2 Emissions       10000 non-null  float64
 14  NOx Emissions       10000 non-null  float64
 15  PM2.5 Emissions     10000 non-null  float64
 16  VOC E

In [4]:
df.isnull().sum()

Vehicle Type          0
Fuel Type             0
Engine Size           0
Age of Vehicle        0
Mileage               0
Speed                 0
Acceleration          0
Road Type             0
Traffic Conditions    0
Temperature           0
Humidity              0
Wind Speed            0
Air Pressure          0
CO2 Emissions         0
NOx Emissions         0
PM2.5 Emissions       0
VOC Emissions         0
SO2 Emissions         0
Emission Level        0
dtype: int64

In [5]:
df.describe()

Engine Size  Age of Vehicle        Mileage         Speed  \
count  10000.000000    10000.000000   10000.000000  10000.000000   
mean       3.369630       14.490000  148995.708000     59.448818   
std        1.495677        8.584339   87068.385915     34.437175   
min        0.800061        0.000000      56.000000      0.000664   
25%        2.080910        7.000000   73589.750000     29.502708   
50%        3.361149       15.000000  148914.500000     59.701114   
75%        4.648033       22.000000  224359.500000     88.499982   
max        5.998532       29.000000  299863.000000    119.974725   

       Acceleration   Temperature      Humidity    Wind Speed  Air Pressure  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean       2.491924     14.935772     50.144758     10.027946   1000.199354   
std        1.446130     14.432900     28.787763      5.735533     28.789590   
min        0.000084     -9.995320      0.000843      0.003425    950.013001   
25%        1.245908      2.331247     25.731917      5.060126    975.096398   
50%        2.482625     15.013688     49.947395     10.052823   1000.787886   
75%        3.747481     27.423980     75.273523     15.044782   1025.092893   
max        4.999861     39.997848     99.993970     19.997502   1049.986720   

       CO2 Emissions  NOx Emissions  PM2.5 Emissions  VOC Emissions  \
count   10000.000000   10000.000000     10000.000000   10000.000000   
mean      273.747254       1.043678         0.105300       0.054611   
std       130.789943       0.548226         0.054933       0.025971   
min        50.045412       0.100056         0.010005       0.010005   
25%       158.448360       0.565941         0.057322       0.031919   
50%       274.734257       1.047428         0.105113       0.054669   
75%       387.958329       1.513206         0.153704       0.076847   
max       499.996419       1.999954         0.199957       0.099993   

       SO2 Emissions  
count   10000.000000  
mean        0.055105  
std         0.026076  
min         0.010005  
25%         0.032710  
50%         0.054948  
75%         0.077687  
max         0.099980

In [6]:
df.drop(columns=["Engine Size","Mileage","Speed","Acceleration","Wind Speed"],inplace=True)
df.head()

Vehicle Type Fuel Type  Age of Vehicle Road Type Traffic Conditions  \
0   Motorcycle  Electric              22   Highway           Moderate   
1          Bus  Electric               3      City              Heavy   
2          Bus    Hybrid              17   Highway          Free flow   
3        Truck  Electric               4     Rural              Heavy   
4        Truck    Hybrid              15   Highway           Moderate   

   Temperature   Humidity  Air Pressure  CO2 Emissions  NOx Emissions  \
0    13.880458  52.883905    955.411642     179.930088       1.085520   
1    19.136947   5.697343   1035.763062     250.505219       1.285628   
2     8.123428   3.953116    976.207064     404.979103       0.258189   
3    35.994893   0.509678    966.919462     463.568608       1.040956   
4    14.793481  52.450884    953.229351      79.514604       1.583390   

   PM2.5 Emissions  VOC Emissions  SO2 Emissions Emission Level  
0         0.011548       0.096207       0.022936         Medium  
1         0.187112       0.073321       0.028021         Medium  
2         0.132398       0.014744       0.075334           High  
3         0.166325       0.093490       0.025324           High  
4         0.078043       0.020396       0.024986            Low

In [7]:
from sklearn.preprocessing import LabelEncoder
LabelEncoder = LabelEncoder()
for i in ["Vehicle Type","Fuel Type","Road Type","Traffic Conditions","Emission Level"]:
  df[i] = LabelEncoder.fit_transform(df[i])
df.head()

Vehicle Type  Fuel Type  Age of Vehicle  Road Type  Traffic Conditions  \
0             2          1              22          1                   2   
1             0          1               3          0                   1   
2             0          2              17          1                   0   
3             3          1               4          2                   1   
4             3          2              15          1                   2   

   Temperature   Humidity  Air Pressure  CO2 Emissions  NOx Emissions  \
0    13.880458  52.883905    955.411642     179.930088       1.085520   
1    19.136947   5.697343   1035.763062     250.505219       1.285628   
2     8.123428   3.953116    976.207064     404.979103       0.258189   
3    35.994893   0.509678    966.919462     463.568608       1.040956   
4    14.793481  52.450884    953.229351      79.514604       1.583390   

   PM2.5 Emissions  VOC Emissions  SO2 Emissions  Emission Level  
0         0.011548       0.096207       0.022936               2  
1         0.187112       0.073321       0.028021               2  
2         0.132398       0.014744       0.075334               0  
3         0.166325       0.093490       0.025324               0  
4         0.078043       0.020396       0.024986               1

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Vehicle Type        10000 non-null  int64  
 1   Fuel Type           10000 non-null  int64  
 2   Age of Vehicle      10000 non-null  int64  
 3   Road Type           10000 non-null  int64  
 4   Traffic Conditions  10000 non-null  int64  
 5   Temperature         10000 non-null  float64
 6   Humidity            10000 non-null  float64
 7   Air Pressure        10000 non-null  float64
 8   CO2 Emissions       10000 non-null  float64
 9   NOx Emissions       10000 non-null  float64
 10  PM2.5 Emissions     10000 non-null  float64
 11  VOC Emissions       10000 non-null  float64
 12  SO2 Emissions       10000 non-null  float64
 13  Emission Level      10000 non-null  int64  
dtypes: float64(8), int64(6)
memory usage: 1.1 MB


In [9]:
x = df.iloc[:,0:13]
x

Vehicle Type  Fuel Type  Age of Vehicle  Road Type  Traffic Conditions  \
0                2          1              22          1                   2   
1                0          1               3          0                   1   
2                0          2              17          1                   0   
3                3          1               4          2                   1   
4                3          2              15          1                   2   
...            ...        ...             ...        ...                 ...   
9995             2          1               1          1                   2   
9996             0          0               5          0                   0   
9997             0          3               8          1                   0   
9998             0          2               2          2                   1   
9999             1          3              15          2                   0   

      Temperature   Humidity  Air Pressure  CO2 Emissions  NOx Emissions  \
0       13.880458  52.883905    955.411642     179.930088       1.085520   
1       19.136947   5.697343   1035.763062     250.505219       1.285628   
2        8.123428   3.953116    976.207064     404.979103       0.258189   
3       35.994893   0.509678    966.919462     463.568608       1.040956   
4       14.793481  52.450884    953.229351      79.514604       1.583390   
...           ...        ...           ...            ...            ...   
9995     0.107381  28.128314   1034.277856     380.616106       0.977784   
9996    37.641697  20.696240    958.678711     135.691599       0.338428   
9997    35.140403  86.267431   1020.702178     315.706170       1.265111   
9998    -6.692706  64.800649   1037.489415     210.794670       0.180733   
9999    16.066580  46.849574    992.132708     422.860000       1.962348   

      PM2.5 Emissions  VOC Emissions  SO2 Emissions  
0            0.011548       0.096207       0.022936  
1            0.187112       0.073321       0.028021  
2            0.132398       0.014744       0.075334  
3            0.166325       0.093490       0.025324  
4            0.078043       0.020396       0.024986  
...               ...            ...            ...  
9995         0.162235       0.089424       0.054463  
9996         0.076185       0.077451       0.099687  
9997         0.082554       0.052279       0.088755  
9998         0.062148       0.077239       0.055793  
9999         0.045526       0.089488       0.062835  

[10000 rows x 13 columns]

In [10]:
y = df['Emission Level']
y

0       2
1       2
2       0
3       0
4       1
       ..
9995    0
9996    1
9997    0
9998    2
9999    0
Name: Emission Level, Length: 10000, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=42)

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
xtrain = sc.fit_transform(xtrain)
xtest = sc.transform(xtest)

In [15]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(xtrain,ytrain)

LogisticRegression()

In [16]:
ypred = model.predict(xtest)
ypred

array([0, 1, 0, ..., 1, 2, 0])

In [17]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
accuracy = accuracy_score(ytest, ypred)
conf_matrix = confusion_matrix(ytest, ypred)
class_report = classification_report(ytest, ypred)

print("Model Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Model Accuracy: 0.9925
Confusion Matrix:
 [[880   0   4]
 [  0 458   3]
 [  1   7 647]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       884
           1       0.98      0.99      0.99       461
           2       0.99      0.99      0.99       655

    accuracy                           0.99      2000
   macro avg       0.99      0.99      0.99      2000
weighted avg       0.99      0.99      0.99      2000



In [19]:
from sklearn.svm import SVC
svm = SVC()
svm.fit(xtrain, ytrain)
ypred = svm.predict(xtest)
print("Using SVM",accuracy_score(ytest,ypred))

Using SVM 0.961


In [20]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(xtrain, ytrain)
ypred = rf.predict(xtest)
print("Using RF",accuracy_score(ytest,ypred))

Using RF 0.9995
